services:
  # Frontend service (Vite)
  frontend:
    build:
      context: .
      target: dev
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://backend:3000
    command: ["npm", "run", "start"]
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - src/server/
        - action: sync
          path: ./public
          target: /app/public
        - action: rebuild
          path: package.json
    depends_on:
      - backend
    networks:
      - app-network

  # Backend service (Express)
  backend:
    build:
      context: .
      target: dev
    ports:
    #  container exposes itself to 3000 and it will be on 3000
    #  for example container could expose itself from 3000 but the service will be found at 3001
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    command: ["npm", "run", "server"]
    develop:
      watch:
        - action: sync+restart
          path: ./src/server
          target: /app/src/server
        - action: rebuild
          path: package.json
    networks:
      - app-network

  # connection string
      
  # this is for the actual database itself the real database 
  db:

    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
    # this port is non negotiable this is what postgres uses always thats from postgres not docker 
    # for example
    # we could say that the container could expose itself from 5432 which is what postges has to do. but it can forward it to a different port 5433
    # - "5432:5433" 
      - "5432:5432"
  
  # this is for the Graphic user interface for pgadmin
  pgadmin:

    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"


networks:
  app-network:
    driver: bridge